export interface ImageAsset {
  section: 'about' | 'branding' | 'other';
  event: string;
  webp: string;
  jpg: string;
  thumbnail: string;
  width: number;
  height: number;
  alt: string;
  /** The photo EventFeature leads with for its event. One per event. */
  featured?: boolean;
}

/**
 * Decorative backdrops for BackdropBand. Sourced stock photography, never
 * a real event photo, so there is no event/thumbnail/lightbox shape to
 * match. Alt is empty on purpose: BackdropBand always renders these behind
 * foreground text, so they are decorative per WCAG. Never place one inside
 * an EventFeature strip, the TileMarquee, or the lightbox.
 */
export interface StockImage {
  id: 'tablescape' | 'buttercream' | 'linen' | 'nashville';
  jpg: string;
  width: number;
  height: number;
  alt: string;
}

export const stockImages: StockImage[] = [
  {
    id: 'tablescape',
    jpg: 'public/images/stock/stock-tablescape.jpg',
    width: 3472,
    height: 4640,
    alt: '',
  },
  {
    id: 'buttercream',
    jpg: 'public/images/stock/stock-buttercream.jpg',
    width: 4000,
    height: 5000,
    alt: '',
  },
  {
    id: 'linen',
    jpg: 'public/images/stock/stock-linen.jpg',
    width: 3448,
    height: 4592,
    alt: '',
  },
  {
    id: 'nashville',
    jpg: 'public/images/stock/stock-nashville.jpg',
    width: 5177,
    height: 3386,
    alt: '',
  },
];

export function findStock(id: StockImage['id']): StockImage {
  const found = stockImages.find((s) => s.id === id);
  if (!found) {
    throw new Error(`Missing stock image ${id}`);
  }
  return found;
}

export const images: ImageAsset[] = [
  // About - Headshots
  {
    section: 'about',
    event: 'headshots',
    webp: 'public/images/about/headshots/headshot-01.webp',
    jpg: 'public/images/about/headshots/headshot-01.jpg',
    thumbnail: 'public/images/about/headshots/headshot-01_thumb.jpg',
    width: 1179,
    height: 1556,
    alt: 'Christina Moore smiling in a black leather jacket on a rooftop terrace, downtown skyline behind her',
  },
  {
    section: 'about',
    event: 'headshots',
    webp: 'public/images/about/headshots/headshot-02.webp',
    jpg: 'public/images/about/headshots/headshot-02.jpg',
    thumbnail: 'public/images/about/headshots/headshot-02_thumb.jpg',
    width: 1246,
    height: 1800,
    alt: 'Christina Moore smiling in a black top on a rooftop terrace, city skyline and train tracks in the background',
  },

  // Branding - White Elephant (Dec 14, 2024)
  {
    section: 'branding',
    event: 'white-elephant',
    webp: 'public/images/branding/white-elephant/white-elephant-01.webp',
    jpg: 'public/images/branding/white-elephant/white-elephant-01.jpg',
    thumbnail: 'public/images/branding/white-elephant/white-elephant-01_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Holiday dinner table set for seven at night, black napkins tied with red ribbon on white plates, a red runner, and a wine bottle nestled in a berry-and-ice centerpiece, city lights through the window',
    featured: true,
  },
  {
    section: 'branding',
    event: 'white-elephant',
    webp: 'public/images/branding/white-elephant/white-elephant-02.webp',
    jpg: 'public/images/branding/white-elephant/white-elephant-02.jpg',
    thumbnail: 'public/images/branding/white-elephant/white-elephant-02_thumb.jpg',
    width: 1013,
    height: 1350,
    alt: 'Daylight view of the same holiday table, black ribbon-tied napkins on white plates around a wood dish of red ornaments and berry sprigs, gift bags and a coat rack in the room behind it',
  },
  {
    section: 'branding',
    event: 'white-elephant',
    webp: 'public/images/branding/white-elephant/white-elephant-03.webp',
    jpg: 'public/images/branding/white-elephant/white-elephant-03.jpg',
    thumbnail: 'public/images/branding/white-elephant/white-elephant-03_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Drink station by the window with liqueur and prosecco bottles, a pitcher of cranberries, a metal bowl of ice, and cocktail straws, a flocked Christmas tree and downtown skyline beside it',
  },
  {
    section: 'branding',
    event: 'white-elephant',
    webp: 'public/images/branding/white-elephant/white-elephant-04.webp',
    jpg: 'public/images/branding/white-elephant/white-elephant-04.jpg',
    thumbnail: 'public/images/branding/white-elephant/white-elephant-04_thumb.jpg',
    width: 1013,
    height: 1350,
    alt: 'Wide view of the holiday table from its head, black-and-red napkin place settings around a wood dish of ornaments and berries, wine chilling in an ice bucket, skyline through the windows',
  },
  {
    section: 'branding',
    event: 'white-elephant',
    webp: 'public/images/branding/white-elephant/white-elephant-05.webp',
    jpg: 'public/images/branding/white-elephant/white-elephant-05.jpg',
    thumbnail: 'public/images/branding/white-elephant/white-elephant-05_thumb.jpg',
    width: 1179,
    height: 1514,
    alt: 'Holiday table set against floor-to-ceiling windows with the downtown skyline behind it, a red runner, black ribbon-tied napkins, and a flocked Christmas tree beside a drink station',
  },

  // Branding - Galentines (Feb 15-16, 2025)
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-01.webp',
    jpg: 'public/images/branding/galentines/galentines-01.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-01_thumb.jpg',
    width: 1013,
    height: 1350,
    alt: 'Pink and red rose table runner set with white scalloped plates and pink Happy Galentine\'s Day place cards',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-02.webp',
    jpg: 'public/images/branding/galentines/galentines-02.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-02_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Wine bottles with custom pink Galentines labels, each tied with a pink ribbon bow',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-03.webp',
    jpg: 'public/images/branding/galentines/galentines-03.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-03_thumb.jpg',
    width: 1013,
    height: 1350,
    alt: 'Red roses and pink confetti scattered across the table next to a glass of red wine',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-04.webp',
    jpg: 'public/images/branding/galentines/galentines-04.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-04_thumb.jpg',
    width: 1013,
    height: 1350,
    alt: 'Rose bottle wrapped in a pink ribbon and stamped with a lipstick-print design, surrounded by red roses',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-05.webp',
    jpg: 'public/images/branding/galentines/galentines-05.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-05_thumb.jpg',
    width: 1013,
    height: 1350,
    alt: 'Wine bottles wrapped in pink ribbon with pink Galentine heart labels and a vase of white roses on a console table, downtown skyline through floor-to-ceiling windows',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-06.webp',
    jpg: 'public/images/branding/galentines/galentines-06.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-06_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Close-up of a pink Happy Galentine\'s Day place card on a scalloped plate with gold flatware',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-07.webp',
    jpg: 'public/images/branding/galentines/galentines-07.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-07_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Row of wine bottles with custom pink Galentines labels lined up along a window overlooking the city',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-08.webp',
    jpg: 'public/images/branding/galentines/galentines-08.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-08_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Overhead view of the Galentine\'s Day tablescape with rose centerpiece, pink runner, and place settings',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-09.webp',
    jpg: 'public/images/branding/galentines/galentines-09.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-09_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Overhead view of a long table set with cream scalloped plates, pink Happy Galentine\'s Day cards, gold flatware, and a center line of red roses flanked by blush and white roses',
    featured: true,
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-10.webp',
    jpg: 'public/images/branding/galentines/galentines-10.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-10_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Pink ribbon-tied wine bottle detail against a view of the downtown skyline',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-11.webp',
    jpg: 'public/images/branding/galentines/galentines-11.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-11_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Table detail with red rose petals and pink confetti scattered across the runner',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-12.webp',
    jpg: 'public/images/branding/galentines/galentines-12.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-12_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Galentine\'s Day place card and pink napkin set on a white scalloped plate',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-13.webp',
    jpg: 'public/images/branding/galentines/galentines-13.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-13_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Pink and red rose table runner set with white scalloped plates and pink Happy Galentine\'s Day place cards',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-14.webp',
    jpg: 'public/images/branding/galentines/galentines-14.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-14_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Wide view of the apartment with the Galentine\'s table set in the foreground, downtown skyline through floor-to-ceiling windows, and a drink station and small pink cake visible in the kitchen behind it',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-15.webp',
    jpg: 'public/images/branding/galentines/galentines-15.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-15_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Red roses and pink confetti scattered across the table next to a glass of red wine',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-16.webp',
    jpg: 'public/images/branding/galentines/galentines-16.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-16_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Rose bottle wrapped in a pink ribbon and stamped with a lipstick-print design, surrounded by red roses',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-17.webp',
    jpg: 'public/images/branding/galentines/galentines-17.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-17_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Overhead close-up of two place settings with pink Happy Galentine\'s Day cards on scalloped plates, a glass of red wine, gold flatware, and a cluster of red and blush roses',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-18.webp',
    jpg: 'public/images/branding/galentines/galentines-18.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-18_thumb.jpg',
    width: 1013,
    height: 1350,
    alt: 'Overhead close-up of a cluster of red roses beside a place setting with a pink Happy Galentine\'s Day card, a glass of red wine, and gold flatware on a pink table runner',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-19.webp',
    jpg: 'public/images/branding/galentines/galentines-19.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-19_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Row of wine bottles with custom pink Galentines labels lined up along a window overlooking the city',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-20.webp',
    jpg: 'public/images/branding/galentines/galentines-20.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-20_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Overhead view of the Galentine\'s Day tablescape with rose centerpiece, pink runner, and place settings',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-21.webp',
    jpg: 'public/images/branding/galentines/galentines-21.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-21_thumb.jpg',
    width: 1012,
    height: 1350,
    alt: 'Bouquet of white, pink, and red roses arranged in a glass vase on the table',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-22.webp',
    jpg: 'public/images/branding/galentines/galentines-22.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-22_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Pink ribbon-tied wine bottle detail against a view of the downtown skyline',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-23.webp',
    jpg: 'public/images/branding/galentines/galentines-23.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-23_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Table detail with red rose petals and pink confetti scattered across the runner',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-24.webp',
    jpg: 'public/images/branding/galentines/galentines-24.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-24_thumb.jpg',
    width: 1012,
    height: 1350,
    alt: 'Galentine\'s Day place card and pink napkin set on a white scalloped plate',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-25.webp',
    jpg: 'public/images/branding/galentines/galentines-25.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-25_thumb.jpg',
    width: 990,
    height: 1800,
    alt: 'Pink and red rose table runner set with white scalloped plates and pink Happy Galentine\'s Day place cards',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-26.webp',
    jpg: 'public/images/branding/galentines/galentines-26.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-26_thumb.jpg',
    width: 1012,
    height: 1350,
    alt: 'Close-up of wine bottles tied with pink ribbon bows and Galentines heart-pattern labels, with a bottle of champagne and red roses behind them',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-27.webp',
    jpg: 'public/images/branding/galentines/galentines-27.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-27_thumb.jpg',
    width: 1012,
    height: 1350,
    alt: 'Red roses and pink confetti scattered across the table next to a glass of red wine',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-28.webp',
    jpg: 'public/images/branding/galentines/galentines-28.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-28_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Rose bottle wrapped in a pink ribbon and stamped with a lipstick-print design, surrounded by red roses',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-29.webp',
    jpg: 'public/images/branding/galentines/galentines-29.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-29_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Pink and burgundy rose bouquet beside a ribbon-wrapped champagne bottle and a stack of Galentine\'s bingo cards',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-30.webp',
    jpg: 'public/images/branding/galentines/galentines-30.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-30_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Close-up of a pink Happy Galentine\'s Day place card on a scalloped plate with gold flatware',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-31.webp',
    jpg: 'public/images/branding/galentines/galentines-31.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-31_thumb.jpg',
    width: 1012,
    height: 1350,
    alt: 'Row of wine bottles with custom pink Galentines labels lined up along a window overlooking the city',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-32.webp',
    jpg: 'public/images/branding/galentines/galentines-32.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-32_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Overhead view of the Galentine\'s Day tablescape with rose centerpiece, pink runner, and place settings',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-33.webp',
    jpg: 'public/images/branding/galentines/galentines-33.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-33_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Bouquet of white, pink, and red roses arranged in a glass vase on the table',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-34.webp',
    jpg: 'public/images/branding/galentines/galentines-34.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-34_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Pink ribbon-tied wine bottle detail against a view of the downtown skyline',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-35.webp',
    jpg: 'public/images/branding/galentines/galentines-35.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-35_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Table detail with red rose petals and pink confetti scattered across the runner',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-36.webp',
    jpg: 'public/images/branding/galentines/galentines-36.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-36_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Galentine\'s Day place card and pink napkin set on a white scalloped plate',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-37.webp',
    jpg: 'public/images/branding/galentines/galentines-37.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-37_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Pink and red rose table runner set with white scalloped plates and pink Happy Galentine\'s Day place cards',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-38.webp',
    jpg: 'public/images/branding/galentines/galentines-38.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-38_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Wine bottles with custom pink Galentines labels, each tied with a pink ribbon bow',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-39.webp',
    jpg: 'public/images/branding/galentines/galentines-39.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-39_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Red roses and pink confetti scattered across the table next to a glass of red wine',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-40.webp',
    jpg: 'public/images/branding/galentines/galentines-40.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-40_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Rose bottle wrapped in a pink ribbon and stamped with a lipstick-print design, surrounded by red roses',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-41.webp',
    jpg: 'public/images/branding/galentines/galentines-41.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-41_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Pink and burgundy rose bouquet beside a ribbon-wrapped champagne bottle and a stack of Galentine\'s bingo cards',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-42.webp',
    jpg: 'public/images/branding/galentines/galentines-42.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-42_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Close-up of a pink Happy Galentine\'s Day place card on a scalloped plate with gold flatware',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-43.webp',
    jpg: 'public/images/branding/galentines/galentines-43.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-43_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Row of wine bottles with custom pink Galentines labels lined up along a window overlooking the city',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-44.webp',
    jpg: 'public/images/branding/galentines/galentines-44.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-44_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Overhead view of the Galentine\'s Day tablescape with rose centerpiece, pink runner, and place settings',
  },
  {
    section: 'branding',
    event: 'galentines',
    webp: 'public/images/branding/galentines/galentines-45.webp',
    jpg: 'public/images/branding/galentines/galentines-45.jpg',
    thumbnail: 'public/images/branding/galentines/galentines-45_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Bouquet of white, pink, and red roses arranged in a glass vase on the table',
  },

  // Other - Bachelorette (Feb 27-28, 2025)
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-01.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-01.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-01_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Welcome to Sara\'s Bachelorette Weekend card held up next to ring pop candy, blue heart sunglasses, and a "But Did You Die" pouch',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-02.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-02.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-02_thumb.jpg',
    width: 1012,
    height: 1350,
    alt: 'Glitter-dipped champagne bottle personalized "from Naviasky to Drussell," tied with a black ribbon bow beside pale blue balloons',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-03.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-03.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-03_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Three folded Nashville sweatshirts lined up with matching drawstring bags, cups, sunglasses, and welcome cards laid out on the floor',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-04.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-04.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-04_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Close-up of a floral zip pouch, a drawstring "But Did You Die" bag, heart-shaped sunglasses, candy, and photo cutouts of the groom',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-05.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-05.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-05_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Welcome to Sara\'s Bachelorette Weekend card resting against blue cowboy boot decor and a ring pop',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-06.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-06.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-06_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Bride flatlay with a rhinestone fedora hat, blue heart sunglasses, a wire "Bride" sign, a white Nashville hoodie, a floral pouch, and a "Mrs. Drussell" sash and veil, BRIDE balloons behind it',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-07.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-07.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-07_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Taco and nacho bar set up on the kitchen island with lime, cilantro, black beans, and lettuce, place cards reading Sara\'s Bachelorette Weekend at each setting',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-08.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-08.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-08_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Five champagne flutes personalized with each guest\'s name in cursive script, beside a rosé bottle labeled "Property of... Mrs. Drussell"',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-09.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-09.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-09_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Six wine bottles in a row on a kitchen counter, each with a different custom bachelorette label reading Sara\'s, Sara\'s Bach, Sara\'s Last Rodeo, or Property of... Mrs. Drussell',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-10.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-10.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-10_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Light and navy blue koozies printed with Sara\'s Last Rodeo, Nashville, TN cowboy boots, fanned out on a table',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-11.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-11.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-11_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Two Sara\'s Last Rodeo, Nashville plastic party cups with a cowboy boots graphic, close up at night',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-12.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-12.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-12_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Welcome to Sara\'s Bachelorette Weekend card held up next to ring pop candy, blue heart sunglasses, and a "But Did You Die" pouch',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-13.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-13.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-13_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Three folded Nashville sweatshirts lined up with matching drawstring bags, cups, sunglasses, and welcome cards laid out on the floor',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-14.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-14.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-14_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Close-up of a floral zip pouch, a drawstring "But Did You Die" bag, heart-shaped sunglasses, candy, and photo cutouts of the groom',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-15.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-15.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-15_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Welcome to Sara\'s Bachelorette Weekend card resting against blue cowboy boot decor and a ring pop',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-16.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-16.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-16_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Bride flatlay with a rhinestone fedora hat, blue heart sunglasses, a wire "Bride" sign, a white Nashville hoodie, a floral pouch, and a "Mrs. Drussell" sash and veil, BRIDE balloons behind it',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-17.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-17.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-17_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Taco and nacho bar set up on the kitchen island with lime, cilantro, black beans, and lettuce, place cards reading Sara\'s Bachelorette Weekend at each setting',
  },
  {
    section: 'other',
    event: 'bachelorette',
    webp: 'public/images/other/bachelorette/bachelorette-18.webp',
    jpg: 'public/images/other/bachelorette/bachelorette-18.jpg',
    thumbnail: 'public/images/other/bachelorette/bachelorette-18_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Six wine bottles in a row, each with a different custom Sara\'s Last Rodeo label, on a kitchen counter',
  },

  // Branding - Friendsgiving (Nov 15-16, 2025)
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-01.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-01.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-01_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Overhead place setting on a woven charger with a scalloped plate, a Friends Giving card reading "I am thankful for...", a red ribbon tie, and a white napkin lettered with a guest\'s name',
    featured: true,
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-02.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-02.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-02_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Espresso martini bar with handwritten instructions and mason jar cocktail shakers',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-03.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-03.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-03_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Wine glasses and a bottle set out on the counter with a red table runner',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-04.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-04.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-04_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Friendsgiving place card on a scalloped plate with a rust-colored napkin',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-05.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-05.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-05_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Espresso martini bar by the window with mason jar shakers, coupe glasses, a stenciled instructions sign, and the downtown skyline behind it',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-06.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-06.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-06_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Dried orange slices and rust-colored napkins scattered across a cheesecloth table runner',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-07.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-07.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-07_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Dried orange garland along a cheesecloth runner with a place card and neutral table setting',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-08.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-08.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-08_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Close-up of the Friendsgiving tablescape with woven chargers and autumnal details',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-09.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-09.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-09_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Cocktail bar detail with mason jars, dried citrus, and a red table runner',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-10.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-10.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-10_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Margarita station on a wood cart with empty mason jars, canned sparkling water, laser-cut margarita signage, and a Happy Friendsgiving 2025 favor box on the shelf below',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-11.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-11.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-11_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Espresso martini bar with handwritten instructions and mason jar cocktail shakers',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-12.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-12.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-12_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Wine glasses and a bottle set out on the counter with a red table runner',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-13.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-13.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-13_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Silver ice bucket on a rust-colored cheesecloth runner beside brown Friends Giving napkins with gold script and a stack of white Friends Giving 2025 can coolers',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-14.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-14.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-14_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Acrylic heart-shaped martini glass charms arranged on a wood surface',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-15.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-15.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-15_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Dried orange slices and rust-colored napkins scattered across a cheesecloth table runner',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-16.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-16.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-16_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Dried orange garland along a cheesecloth runner with a place card and neutral table setting',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-17.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-17.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-17_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Close-up of the Friendsgiving tablescape with woven chargers and autumnal details',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-18.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-18.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-18_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Cocktail bar detail with mason jars, dried citrus, and a red table runner',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-19.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-19.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-19_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Place setting with a Friendsgiving card and a named linen napkin on a woven charger',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-20.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-20.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-20_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Espresso martini bar with handwritten instructions and mason jar cocktail shakers',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-21.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-21.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-21_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Wine glasses and a bottle set out on the counter with a red table runner',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-22.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-22.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-22_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Friendsgiving place card on a scalloped plate with a rust-colored napkin',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-23.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-23.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-23_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Acrylic heart-shaped martini glass charms arranged on a wood surface',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-24.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-24.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-24_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Dried orange slices and rust-colored napkins scattered across a cheesecloth table runner',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-25.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-25.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-25_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Dried orange garland along a cheesecloth runner with a place card and neutral table setting',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-26.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-26.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-26_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Close-up of the Friendsgiving tablescape with woven chargers and autumnal details',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-27.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-27.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-27_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Cocktail bar detail with mason jars, dried citrus, and a red table runner',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-28.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-28.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-28_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Place setting with a Friendsgiving card and a named linen napkin on a woven charger',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-29.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-29.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-29_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Espresso martini bar with handwritten instructions and mason jar cocktail shakers',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-30.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-30.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-30_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Wine glasses and a bottle set out on the counter with a red table runner',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-31.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-31.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-31_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Friendsgiving place card on a scalloped plate with a rust-colored napkin',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-32.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-32.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-32_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Acrylic heart-shaped martini glass charms arranged on a wood surface',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-33.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-33.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-33_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Wide overhead view of the full Friendsgiving table set for nine, woven chargers and named place cards around a dried orange garland and a candle-and-wine centerpiece',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-34.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-34.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-34_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Dried orange garland along a cheesecloth runner with a place card and neutral table setting',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-35.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-35.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-35_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Table close-up with a wine bottle set in a citrus-studded centerpiece, dried orange garland, and place settings tied in red ribbon on a cream cheesecloth runner',
  },
  {
    section: 'branding',
    event: 'friendsgiving',
    webp: 'public/images/branding/friendsgiving/friendsgiving-36.webp',
    jpg: 'public/images/branding/friendsgiving/friendsgiving-36.jpg',
    thumbnail: 'public/images/branding/friendsgiving/friendsgiving-36_thumb.jpg',
    width: 1350,
    height: 1800,
    alt: 'Cocktail bar detail with mason jars, dried citrus, and a red table runner',
  },

  // Other - Curated Gifting (Apr 14, 2025)
  {
    section: 'other',
    event: 'curated-gifting',
    webp: 'public/images/other/curated-gifting/curated-gifting-01.webp',
    jpg: 'public/images/other/curated-gifting/curated-gifting-01.jpg',
    thumbnail: 'public/images/other/curated-gifting/curated-gifting-01_thumb.jpg',
    width: 1012,
    height: 1350,
    alt: 'Custom light-blue UConn hoodie hanging in a kitchen, back printed with a repeating stacked UCONN wordmark',
  },
  {
    section: 'other',
    event: 'curated-gifting',
    webp: 'public/images/other/curated-gifting/curated-gifting-02.webp',
    jpg: 'public/images/other/curated-gifting/curated-gifting-02.jpg',
    thumbnail: 'public/images/other/curated-gifting/curated-gifting-02_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Custom light-blue UConn quarter-zip pullover on a hanger, close-up of the UCONN wordmark on the chest',
  },
  {
    section: 'other',
    event: 'curated-gifting',
    webp: 'public/images/other/curated-gifting/curated-gifting-03.webp',
    jpg: 'public/images/other/curated-gifting/curated-gifting-03.jpg',
    thumbnail: 'public/images/other/curated-gifting/curated-gifting-03_thumb.jpg',
    width: 1012,
    height: 1350,
    alt: 'Back of a custom light-blue UConn hoodie printed with a Connecticut Huskies mascot design over a repeating UCONN text pattern',
  },
  {
    section: 'other',
    event: 'curated-gifting',
    webp: 'public/images/other/curated-gifting/curated-gifting-04.webp',
    jpg: 'public/images/other/curated-gifting/curated-gifting-04.jpg',
    thumbnail: 'public/images/other/curated-gifting/curated-gifting-04_thumb.jpg',
    width: 1800,
    height: 1350,
    alt: 'Custom UConn Huskies design with "Connecticut" arched above and "Huskies" arched below a husky mascot illustration, over a repeating UCONN text pattern',
    featured: true,
  },

  // Other - Graphic Design Portfolio
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-01.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-01.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-01_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Custom Curations wordmark logo on an orange and pink plaid pattern',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-02.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-02.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-02_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Custom curations by Christina wordmark logo on a tan and rose plaid pattern',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-03.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-03.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-03_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Sara\'s Bachelorette, Nashville, Tennessee logo with a pair of cowboy boots, in blue',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-04.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-04.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-04_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Sara\'s Last Rodeo, Nashville, TN arched badge logo with a cowboy boot and hat illustration, in navy on pale blue',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-05.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-05.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-05_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Sara\'s Last Rodeo, Nashville, TN circular badge logo with a cowboy boot and hat illustration, in navy',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-06.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-06.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-06_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Tennessee state outline with Volunteers script, filled with an orange and cream collage pattern of florals and game-day icons',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-07.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-07.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-07_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Titans Tennessee script over a navy, red, and light-blue checkered pattern',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-08.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-08.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-08_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Maryland wordmark over the state\'s outline filled with a red sequin pattern',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-09.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-09.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-09_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Tennessee Titans script over a navy, red, and light-blue checkered pattern banner',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-10.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-10.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-10_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Philadelphia Eagles script over a teal, black, and grey checkered pattern banner',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-11.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-11.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-11_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Eagles Philadelphia hand-lettered logo over a repeating teal and grey Philadelphia Eagles text pattern',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-12.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-12.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-12_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Philadelphia Eagles logo badge over a repeating text pattern, in teal and slate blue',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-13.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-13.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-13_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Philadelphia skyline illustration with an Eagles Philadelphia hand-lettered logo, in teal',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-14.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-14.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-14_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Dog silhouette filled with an orange football tailgate collage pattern of flowers, footballs, and pennants',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-15.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-15.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-15_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Tennessee wordmark in the shape of the state, filled with an orange football tailgate collage pattern',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-16.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-16.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-16_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Sunday Funday bubble-letter logo filled with a red, white, and blue sports collage pattern',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-17.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-17.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-17_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Sunday Funday bubble-letter logo filled with a red and blue floral pattern, with a dashed underline',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-18.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-18.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-18_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Tennessee state outline with Tennessee Titans script over a pink and blue floral sports collage pattern',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-19.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-19.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-19_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Sunday Funday vertical logo in maroon and gold, with a floral collage fill and dashed divider',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-20.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-20.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-20_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Tennessee state outline with Nashville Predators wordmark over a navy and gold hockey-themed collage pattern with a numbered jersey',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-21.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-21.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-21_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Repeating Nashville wordmark pattern in retro bubble lettering, in red, maroon, and pink florals',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-22.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-22.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-22_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Margaritas and Matrimony logo with a line-art cocktail glass and citrus wedge, in peach',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-23.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-23.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-23_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Margs Matrimony repeating wordmark pattern in green and orange colorways',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-24.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-24.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-24_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Margaritas and Matrimony logo with a line-art citrus wedge illustration, in forest green',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-25.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-25.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-25_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Margaritas and Matrimony logo with a line-art citrus wedge illustration, in burnt orange',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-26.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-26.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-26_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Sara Found Her Perfect Match circular badge logo with a matchbox illustration, in orange',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-27.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-27.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-27_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Sara Found Her Match arched badge logo with a love and flame matchbox illustration and Nashville, TN | Feb 2025, in coral and burgundy',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-28.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-28.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-28_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Sara Found Her Match arched badge logo with a love and flame matchbox illustration and Nashville, TN | Feb 2025, in pink and coral',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-29.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-29.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-29_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Welcome to Sara\'s Bachelorette Weekend logo over a repeating Sara\'s Bachelorette text pattern, in navy and light blue',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-30.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-30.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-30_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Sara\'s Last Rodeo, Nashville, TN, Feb 2025 arched badge logo with a cowboy boot and hat illustration, in blue',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-31.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-31.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-31_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Friendsgiving 2025 wordmark logo inside a hand-drawn leaf wreath, in tan on a burgundy background',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-32.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-32.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-32_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Friendsgiving 2025 wordmark logo inside a hand-drawn leaf wreath, in brown on a blush background',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-33.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-33.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-33_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Galentines wordmark banner over a burgundy heart-pattern background',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-34.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-34.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-34_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Happy Birthday Sana logo over a pink floral illustration',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-35.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-35.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-35_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Sara\'s Bachelorette logo over a blue line-art floral illustration',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-36.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-36.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-36_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'From Miss To Mrs. logo with a ribbon-tied champagne coupe illustration, in black and white',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-37.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-37.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-37_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'From Naviasky To Drussell logo with a ribbon-tied champagne coupe illustration, in black and white',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-38.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-38.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-38_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Property of... Mrs. Drussell logo over a grey line-art floral illustration',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-39.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-39.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-39_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Repeating Thank You wordmark pattern in maroon and blush',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-40.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-40.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-40_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Anna and Brandon, 06.21.2025 wedding monogram with a line-art champagne toast illustration and a leaf wreath, in pale blue',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-41.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-41.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-41_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Congratulations Angie and Alec, 05.17.2025 wedding announcement over a watercolor floral illustration',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-42.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-42.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-42_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Happy Mother\'s Day logo over a repeating pink floral pattern',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-43.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-43.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-43_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Thank You logo over a watercolor floral illustration, in maroon and blush',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-44.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-44.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-44_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Happy Birthday Sarah logo over a blue line-art hydrangea illustration',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-45.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-45.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-45_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Four-team crest mashup combining Maryland, UConn Huskies, Golden State Warriors, and New York Mets logos',
  },
  {
    section: 'other',
    event: 'graphic-design',
    webp: 'public/images/other/graphic-design/graphic-design-46.webp',
    jpg: 'public/images/other/graphic-design/graphic-design-46.jpg',
    thumbnail: 'public/images/other/graphic-design/graphic-design-46_thumb.jpg',
    width: 688,
    height: 688,
    alt: 'Four-team crest mashup combining UConn Huskies, New York Knicks, Harvard Crimson, and New York Jets logos',
  },
];
